import Head from 'next/head'
import ArticleList from '../Components/ArticleList';

export default function Home({ articles }) {
    console.log(articles)
    return (
        <div>
            <Head>
                <title>Next Js</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/vercel.svg" />
            </Head>

            <ArticleList articles = {articles}/>
        </div>
    )
}


export const getStaticProps = async () => {
    const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=10`)
    const articles = await res.json()

    return {
        props: {
            articles,
        },
    }
}